
export const ADD_TODO_ITEM_START = 'ADD_TODO_ITEM_START';
export const ADD_TODO_ITEM_SUCCES = 'ADD_TODO_ITEM_SUCCESS';
export const ADD_TODO_ITEM_FAIL = 'ADD_TODO_ITEM_FAIL';

export const REMOVE_TODO_ITEM_START = 'REMOVE_TODO_ITEM_START';
export const REMOVE_TODO_ITEM_SUCCES = 'REMOVE_TODO_ITEM_SUCCESS';
export const REMOVE_TODO_ITEM_FAIL = 'REMOVE_TODO_ITEM_FAIL';

export const COMPLETE_TODO_ITEM_START = 'COMPLETE_TODO_ITEM_START';
export const COMPLETE_TODO_ITEM_SUCCES = 'COMPLETE_TODO_ITEM_SUCCESS';
export const COMPLETE_TODO_ITEM_FAIL = 'COMPLETE_TODO_ITEM_FAIL';

export const CLEAR_COMPLETE_TODO_ITEMS = 'CLEAR_COMPLETE_TODO_ITEMS';

export const FETCH_TODO_ITEMS_START = 'FETCH_TODO_ITEMS_START';
export const FETCH_TODO_ITEMS_SUCCESS = 'FETCH_TODO_ITEMS_SUCCESS';
export const FETCH_TODO_ITEMS_FAIL = 'FETCH_TODO_ITEMS_FAIL';

export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAIL = 'AUTHENTICATION_FAIL';
