export const ADD_TOOD_ITEM = 'ADD_TOOD_ITEM';
export const REMOVE_TOOD_ITEM = 'REMOVE_TOOD_ITEM';
export const COMPLETE_TOOD_ITEM = 'COMPLETE_TOOD_ITEM';
export const CLEAR_COMPLETE_TOOD_ITEMS = 'CLEAR_COMPLETE_TOOD_ITEMS';