
export const ADD_TODO_ITEM_START = 'ADD_TODO_ITEM_START';
export const ADD_TODO_ITEM_SUCCES = 'ADD_TODO_ITEM_SUCCES';
export const ADD_TODO_ITEM_FAIL = 'ADD_TODO_ITEM_FAIL';

export const REMOVE_TODO_ITEM_START = 'REMOVE_TODO_ITEM_START';
export const REMOVE_TODO_ITEM_SUCCES = 'REMOVE_TODO_ITEM_SUCCES';
export const REMOVE_TODO_ITEM_FAIL = 'REMOVE_TODO_ITEM_FAIL';

export const COMPLETE_TODO_ITEM_START = 'COMPLETE_TODO_ITEM_START';
export const COMPLETE_TODO_ITEM_SUCCES = 'COMPLETE_TODO_ITEM_SUCCES';
export const COMPLETE_TODO_ITEM_FAIL = 'COMPLETE_TODO_ITEM_FAIL';

export const CLEAR_COMPLETE_TODO_ITEMS = 'CLEAR_COMPLETE_TODO_ITEMS';
